export const cuisines = [
    "Indian",
    "North Indian",
    "South Indian",
    "Punjabi",
    "Gujarati",
    "Rajasthani",
    "Bengali",
    "Maharashtrian",
    "Hyderabadi",
    "Mughlai",
    "Awadhi",
    "Lucknowi",
    "Kashmiri",
    "Goan",
    "Kerala",
    "Chettinad",
    "Chinese",
    "Indo-Chinese",
    "Thai",
    "Japanese",
    "Korean",
    "Vietnamese",
    "Italian",
    "Mexican",
    "American",
    "Continental",
    "Mediterranean",
    "French",
    "Spanish",
    "Greek",
    "Turkish",
    "Lebanese",
    "Arabian",
    "Afghani",
    "Tibetan",
    "Nepalese",
    "Malaysian",
    "Singaporean",
    "Fast Food",
    "Street Food",
    "Cafe",
    "Bakery",
    "Desserts",
    "Ice Cream",
    "Pizza",
    "Burger",
    "Sandwich",
    "Rolls",
    "Biryani",
    "Seafood",
    "Barbecue",
    "Healthy Food",
    "Salads",
    "Vegetarian",
    "Vegan",
    "Jain",
    "Beverages",
    "Juices",
    "Tea",
    "Coffee",
];